/*
 * generated by Xtext 2.28.0
 */
package gameoflife.tasks.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTaskDSLScopeProvider extends DelegatingScopeProvider {
}
