/**
 * generated by Xtext 2.28.0
 */
package gameoflife.tasks.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TaskDSLIdeModule extends AbstractTaskDSLIdeModule {
}
