/**
 * generated by Xtext 2.28.0
 */
package gameoflife.tasks.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import gameoflife.tasks.TaskDSLRuntimeModule;
import gameoflife.tasks.TaskDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TaskDSLIdeSetup extends TaskDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    TaskDSLRuntimeModule _taskDSLRuntimeModule = new TaskDSLRuntimeModule();
    TaskDSLIdeModule _taskDSLIdeModule = new TaskDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_taskDSLRuntimeModule, _taskDSLIdeModule));
  }
}
