/*
 * generated by Xtext 2.28.0
 */
package gameoflife.tasks.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TaskDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("gameoflife/tasks/parser/antlr/internal/InternalTaskDSL.tokens");
	}
}
