/**
 * generated by Xtext 2.28.0
 */
package gameoflife.tasks;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TaskDSLStandaloneSetup extends TaskDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new TaskDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
